### ISSUE TITLE
disques问题

### ISSUE THREAD

**Issue by chenjian158978** [mritd/mritd.me#2]
看到你设置里面有
-  disqus_username： mritd

然后在`_layouts/post.html`中写了加载`_includes/comments.html`，从而加载disqus评论插件。

我同样的没有成功，提示：**Disqus seems to be taking longer than usual. Reload?**

问下你的名字，就是在[https://disqus.com/home/settings/account/](url)中的`Username`填写的是`mritd`，还是怎么样填写？
或者需要别的设置？

**Comment by mritd** [comment]
直接写的 mritd
